### PR TITLE
Home page grid buttons with nav bar

### LINKED ISSUE #20: Create grids on homepage with clickable images

### PR DESCRIPTION
**Pull request by jerpyk**
Closes #20 
- Combines nav bar update with grid buttons
- Functionality for the buttons not yet added

### CODE REVIEW

**Comment by Cheekane** [comment]
@jerpyk 
Functionality for each button will be added in separate PRs. It's looking really good, nice work.

**Comment by junoocha** [comment]
Bug:
Grid doesn't properly account for displays larger than 1200 x 700 px

e.g. 1920 by 1080

image

**Review by Lunchii — APPROVED** [review]
🧠

**Review by Cheekane — CHANGES_REQUESTED** [review]
@jerpyk 
We need changes.
1. Make the grid into a component.
2. Each "circle" should also be a component of the grid.
3. Make sure the grid works for all resolutions.

**Review by jerpyk — COMMENTED** [review]
fixed

**Comment by Cheekane** [comment]
@jerpyk When you make a update/fix and want us to review, press the re-review button.
Screenshot 2024-12-27 at 10 58 40 PM

**Pull request closed without merging**
