### PR TITLE
Refactor NavBar

### LINKED ISSUE #56: Change navbar
Navbar should have `connect`, `contact`, `events`, and `login`

### PR DESCRIPTION
**Pull request by Cheekane**
Closes #56 
## Overview
Refactored NavBar component.
+ Redesigned NavBar
+ Added SideBar (Mobile view for NavBar)
+ You can click outside from the SideBar to close it

## Note
- The colors for the icons and text are not the best, but we will change them later.
- The majority of the added lines of code is from the `LKPC_Logo.svg`, we will change it later.

## Test

https://github.com/user-attachments/assets/fd6b8c25-bdea-478d-862d-f66e6e343f99

### CODE REVIEW

**Review by ZestyScrubz — DISMISSED** [review]
The colours are a little weird with the icons but we can change that later.  👍 Approve

**Comment by Cheekane** [comment]
> The colours are a little weird with the icons but we can change that later. 👍 Approve

Agreed

**Review by ZestyScrubz — DISMISSED** [review]
👌

**Review by jerpyk — COMMENTED** [review]
nice, but logo is no longer clickable, and home page without the `/home` in the url has nothing now (no half divided screen)
Screenshot 2024-12-28 at 10 34 48 PM

**Comment by Cheekane** [comment]
## Update
+ Made `SideBar` icons white
+ New `routeDefinitions.ts` constant for the paths (use this/add too it)
+ Logo and links now navigate to pages
+ Added some transitions to the desktop view hover on `NavBar`

Screenshot 2024-12-29 at 12 58 15 AM

**Review by jerpyk — DISMISSED** [review]
👍

**Review by jerpyk — DISMISSED** [review]
👍

**Review by Lunchii — CHANGES_REQUESTED** [review]
I think the navigation bar items should be much closer because it might be annoying to press and they could be a bit lower. 
Also it breaks again at the smallest size (320px) because the font size doesnt change anymore (unless you didnt merge with my fix)

**Review by jerpyk — DISMISSED** [review]
👍

**Pull request merged**
